const { test } = require('node:test');
const assert = require('node:assert/strict');
const { Client } = require('pg');
const { randomUUID } = require('node:crypto');
const { Database } = require('../server/database');
const { createServer } = require('../server/index');
test('real Postgres transactions, retry receipts, conflicts, recovery and HTTP boundaries', { skip: !process.env.TEST_DATABASE_URL }, async t => {
    const schema = `test_${randomUUID().replaceAll('-', '')}`;
    const admin = new Client({ connectionString: process.env.TEST_DATABASE_URL });
    await admin.connect();
    await admin.query(`CREATE SCHEMA "${schema}"`);
    const db = new Database({ connectionString: process.env.TEST_DATABASE_URL, options: `-c search_path=${schema}` });
    t.after(async () => { await db.close(); await admin.query(`DROP SCHEMA "${schema}" CASCADE`); await admin.end(); });
    const value = { id: 'task-1', name: 'Original', created: '2026-09-12T12:00:00.000Z', completions: {} };
    const op = { opId: 'create-1', kind: 'task', key: value.id, base: null, value, baseRevision: 0 };
    const saved = await db.sync([op]);
    const retried = await db.sync([op], saved.databaseId);
    assert.equal(retried.revision, saved.revision);
    assert.equal(retried.records.length, 1);
    const edit = { ...op, opId: 'edit-1', base: value, value: { ...value, name: 'Edited' }, baseRevision: saved.revision };
    await db.sync([edit], saved.databaseId);
    const conflict = await db.sync([{ ...edit, opId: 'competing', value: { ...value, name: 'Competing' } }], saved.databaseId);
    assert.equal(conflict.results[0].status, 'conflict');
    assert.equal(conflict.records[0].value.name, 'Edited');
    const beforeRollback = conflict.revision;
    await assert.rejects(db.sync([{ ...edit, opId: 'rolled-back', base: edit.value, value: { ...value, name: 'Must roll back' } }, { ...op, value: { ...value, name: 'ID reuse' } }], saved.databaseId));
    assert.equal((await db.sync([], saved.databaseId)).revision, beforeRollback);
    await assert.rejects(db.sync([], randomUUID()), /database has changed/);
    await db.sync([{ ...edit, opId: 'delete-1', base: edit.value, value: null }], saved.databaseId);
    assert.equal((await db.sync([], saved.databaseId)).records[0].value, null);
    assert.equal((await db.sync([{ ...edit, opId: 'stale' }], saved.databaseId)).results[0].status, 'conflict');

    const port = 14317;
    const server = createServer(db, port);
    await new Promise((resolve, reject) => { server.once('error', reject); server.listen(port, '127.0.0.1', resolve); });
    t.after(() => new Promise(resolve => server.close(resolve)));
    const url = `http://localhost:${port}`;
    assert.equal((await fetch(url)).status, 200);
    assert.equal((await fetch(`${url}/.local/database.json`)).status, 404);
    assert.equal((await fetch(`${url}/server/config.js`)).status, 404);
    assert.equal((await fetch(`${url}/api/sync`, { method: 'POST', body: '{}' })).status, 403);
    const headers = { Origin: url, 'X-Tracker-Client': '1', 'Content-Type': 'application/json' };
    const response = await fetch(`${url}/api/sync`, { method: 'POST', headers, body: JSON.stringify({ operations: [] }) });
    assert.equal(response.status, 200);
    assert.equal((await response.json()).records[0].value, null);
    assert.equal((await fetch(`${url}/api/sync`, { method: 'POST', headers, body: '{bad' })).status, 400);
});
